PlayerManager:
  join:
    message-join: "&7[&a+&7] &r%player%"
    welcome-message: "&aBienvenue à toi !"
    message-custom-re-join: "AH ! Te re-voilà !"
  quit:
    message-quit: "&7[&c-&7] &r%player%"
Faction:
  #Prix pour créer une faction (possible de rien payer avec la permission bypass)
  price-to-create-faction: 10000
  slots: 8
ban-word-name-faction:
  - jobless
  - joblife
chat-format: #Pour les couleurs tu as le choix avec '§' ou '&', (recommend '§')
    #Diponible aussi %hour% pour mettre l'heure
    with-faction: "&7%faction% &r[%grade%&r] %player% >> %message%"
    without-faction: "[%grade%] %player% >> %message%"
    #ceci permet aux personnes qui auront cette permission vont pouvoir mettre des couleurs dans leurs messages
    permission-chat-color: chat.color
#Rajouter du power avec le temps,
#ceci vous permet de rajouter du power au joueur grace au temps de jeu le temps que vous mettez n'est pas accumulable.
#Si une personne est présente 2 h et vous vous mettez pour 1h = 1 power elle va gagner que 1 de power.
#Suivez l'exemple pour ne pas avoir d'erreur.
power:
  #le nom que tu veux peu importe
  hour:
    time: 60 #en minutes
    power: 1 #le nombre de power gagné
  2:
    time: 120
    power: 2
  3:
    time: 180
    power: 3